# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='proto.test',
  syntax='proto2',
  serialized_pb=_b('\n\ntest.proto\x12\nproto.test\"g\n\x06t_info\x12\x0c\n\x04year\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\r\x12\x0c\n\x04hour\x18\x04 \x01(\r\x12\x0b\n\x03min\x18\x05 \x01(\r\x12\x0b\n\x03sec\x18\x06 \x01(\r\x12\x0b\n\x03\x66mt\x18\x07 \x01(\t\"`\n\rmsg_heartbeat\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12 \n\x04info\x18\x02 \x01(\x0b\x32\x12.proto.test.t_info\x12\x0f\n\x07padding\x18\x03 \x01(\t\x12\r\n\x05\x61rray\x18\x04 \x03(\x04*8\n\ne_cmd_code\x12\x14\n\x10\x63\x63_c2g_heartbeat\x10\x01\x12\x14\n\x10\x63\x63_g2c_heartbeat\x10\x02')
)

_E_CMD_CODE = _descriptor.EnumDescriptor(
  name='e_cmd_code',
  full_name='proto.test.e_cmd_code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='cc_c2g_heartbeat', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='cc_g2c_heartbeat', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=229,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_E_CMD_CODE)

e_cmd_code = enum_type_wrapper.EnumTypeWrapper(_E_CMD_CODE)
cc_c2g_heartbeat = 1
cc_g2c_heartbeat = 2



_T_INFO = _descriptor.Descriptor(
  name='t_info',
  full_name='proto.test.t_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='proto.test.t_info.year', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='month', full_name='proto.test.t_info.month', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='day', full_name='proto.test.t_info.day', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hour', full_name='proto.test.t_info.hour', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='proto.test.t_info.min', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sec', full_name='proto.test.t_info.sec', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fmt', full_name='proto.test.t_info.fmt', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=129,
)


_MSG_HEARTBEAT = _descriptor.Descriptor(
  name='msg_heartbeat',
  full_name='proto.test.msg_heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='proto.test.msg_heartbeat.count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='proto.test.msg_heartbeat.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='padding', full_name='proto.test.msg_heartbeat.padding', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='array', full_name='proto.test.msg_heartbeat.array', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=227,
)

_MSG_HEARTBEAT.fields_by_name['info'].message_type = _T_INFO
DESCRIPTOR.message_types_by_name['t_info'] = _T_INFO
DESCRIPTOR.message_types_by_name['msg_heartbeat'] = _MSG_HEARTBEAT
DESCRIPTOR.enum_types_by_name['e_cmd_code'] = _E_CMD_CODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

t_info = _reflection.GeneratedProtocolMessageType('t_info', (_message.Message,), dict(
  DESCRIPTOR = _T_INFO,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:proto.test.t_info)
  ))
_sym_db.RegisterMessage(t_info)

msg_heartbeat = _reflection.GeneratedProtocolMessageType('msg_heartbeat', (_message.Message,), dict(
  DESCRIPTOR = _MSG_HEARTBEAT,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:proto.test.msg_heartbeat)
  ))
_sym_db.RegisterMessage(msg_heartbeat)


# @@protoc_insertion_point(module_scope)
